name: BuildLangs

on:
  workflow_dispatch:
    inputs:
      version:
        description: '输入版本'
        default: 'v4.5'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run build-langs
        run: |
          chmod +x ./build-langs.sh; ./build-langs.sh

      - name: Generate release tag
        id: tag
        if: true && !failure() && !cancelled()
        run: |
          echo "::set-output name=release_tag::${{ inputs.version }}-$(date +"%s")"
          echo "::set-output name=status::success"

      - name: Upload  to release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled() && !failure()
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ./gl-router-sdk-languages.zip

