name: BuildLangs

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run build-langs
        run: |
          chmod u+rwx ./build-langs.sh

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: ${{ env.FIRMWARE }}/dist.zip

