name: BuildLangs

on:
  push:
    branches: [ "release" ]

  workflow_dispatch:
    tags:
          description: 'Test tags'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run build-langs
        run: |
        ./build-langs.sh

